name: CI tests

on:
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    env:
      CI: true
      NODE_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}

      - name: Log node version
        run: node --version

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tsc
        run: yarn tsc

      - name: Run build
        run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev:ci
          wait-on: 'http://localhost:3000, http://localhost:7007'
          project: ./packages/app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify:
    env:
      NODE_OPTIONS: --max-old-space-size=4096

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}

      - name: Log node version
        run: node --version

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run prettier
        run: yarn prettier --check .

      - name: Run tsc
        run: yarn tsc

      - name: Run build
        run: yarn build

      - name: Run test
        run: yarn test
